### ISSUE TITLE
Consider refactor futrher the project structure

### ISSUE THREAD

**Issue by deepalma** [reactivate-ldn/elm-workshop-voting#2]
This is the current dependency tree of the app (excluding library and third parties modules):
```
Main
    Message
        Model
    Model
    Request
        Decoder
        Message
    Subscriptions
        Model
        Message
    Update
        Decoder
        Message
        Model
        Request
    View
        Chart
        Message
        Model
```

And this is the current folder structure for `src`:
```
app
    chart.elm
    decoder.elm
    message.elm
    model.elm
    request.elm
    subscriptions.elm
    update.elm
    view.elm
```

I think we should try to separate in some way the code into `request.elm` and `decoder.elm` from the rest to help people creating a mental app of the elm architecture.
Also I would like to merge `chart.elm` into `view.elm`, and eventually move the styles in a `styles` folder.

One proposal could be the following:
```
app
    message.elm
    model.elm
    subscriptions.elm
    update.elm
    view.elm (<< chart.elm w/o styles)
styles
    view.styles.elm
Main.elm (<< request.elm & decoder.elm)
```

Another similar solution will be keeping `Main.elm` as it is now, and merge `request.elm` and `decoder.elm` into a single file (app.elm ?) inside the `app` folder.

I honestly prefer the first approach, my only concern is that we will have to expose `postAnswer` from the `Main.elm` in order to satisfy the dependency in `update.elm`.

Let me know if you agree and which approach do you prefer eventually.
I'll be happy to create a PR for it.

**Comment by alex3165** [comment]
Agree, except for separating the styles from the view into a file, I would instead go for https://github.com/styled-components/elm-styled and transform the styles into standalone components, any thought ?

**Comment by kitten** [comment]
@alex3165 I don't know how stable Konstantin's take on SC is, but we can give it a go

**Comment by deepalma** [comment]
I checked quickly both elm-style and elm-css but I missed this! I quite like styled component so I guess we can try. I had the feeling that at the moment the more adopted approach is to go with elm-css though.

**Comment by deepalma** [comment]
#4 Address the files refactor (no styled components yet)

**Comment by alex3165** [comment]
👍

**Comment by deepalma** [comment]
If I run `elm-package install styled-components/elm-styled` I got this error:
```
Error: Could not find any packages named styled-components/elm-styled.

Here are some packages that have similar names:

    elm-community/elm-time
    seanhess/elm-style
    elm-community/elm-test
    poying/elm-style

Maybe you want one of those?
```

Is the same for you guys?
